import streamlit as st
import pandas as pd
import os
import time

# Configure the page layout
st.set_page_config(page_title="Sozo SOC Dashboard", layout="wide")

# Header Section
st.title("Project Sozo: Autonomous Security Operations Center")
st.markdown("Real-time telemetry and threat intelligence monitoring.")
st.markdown("---")

def load_threat_intel():
    """Reads the active firewall blocklist generated by the SOAR engine."""
    if os.path.exists('memory_blacklist.txt'):
        with open('memory_blacklist.txt', 'r') as f:
            ips = f.read().splitlines()
            return [ip for ip in ips if ip.strip()]
    return []

# Fetch current data
blacklisted_ips = load_threat_intel()

# Top-level Metrics
col1, col2, col3 = st.columns(3)

with col1:
    st.metric(label="Active Threats Blocked (Layer 3)", value=len(blacklisted_ips))

with col2:
    st.metric(label="Innate Detection Engine", value="Active")

with col3:
    st.metric(label="Adaptive ML Engine", value="Online")

st.markdown("---")

# Main Content Area
left_column, right_column = st.columns(2)

with left_column:
    st.subheader("Active Threat Intelligence Feed")
    st.markdown("IP addresses dynamically isolated by the automated response engine.")
    
    if blacklisted_ips:
        df_ips = pd.DataFrame(blacklisted_ips, columns=["Blacklisted IP Address"])
        st.dataframe(df_ips, width='stretch')
    else:
        st.info("No active threats currently isolated.")

with right_column:
    st.subheader("Adaptive Engine Telemetry")
    st.markdown("Performance metrics from the Isolation Forest anomaly detection model.")
    
    # Simulating the static metrics retrieved from our Phase 2 testing
    metrics_data = {
        "Metric": ["Baseline Training Flows", "Evaluation Sample Size", "Detected Anomalies", "Anomaly Detection Rate"],
        "Value": ["50,000", "20,000", "179", "0.90%"]
    }
    df_metrics = pd.DataFrame(metrics_data)
    st.table(df_metrics)

# Auto-refresh mechanism to keep the dashboard live
time.sleep(2)
st.rerun()